import React from "react";
import ServicesLanding from "../../components/Services/ServicesLanding";
import bigDataImg from "../../assets/BigData/BigData.png";
import SimpleCard from "../../components/CommonComps/SimpleCard";
import LetsConnect from "../../components/ContactUs/LetsConnect";
import WhyBigData from "../../components/Services/BigData/WhyBigData";
import BigFocus from "../../components/Services/BigData/BigFocus";
function BigDataPage() {
  return (
    <>
      <ServicesLanding
        title={"Big Data"}
        content={
          "Harness the Power of Big Data for Scalable and Accurate Insights"
        }
        btnText={"Contact Us"}
        sideImg={bigDataImg}
      />
      <SimpleCard
        text={
          "Data is rapidly growing every second and becoming crucial these days. We need to get faster and accurate responses. NeuSpaarX uses several Big Data technologies to provide faster, accurate and scalable solutions. Big data refers to large volumes of structured and unstructured data that are generated by businesses, governments, and other organizations. This data can come from a variety of sources, such as transactions, social media, sensors, and log files."
        }
        className="my-20 mx-[5vw]"
      />
      <BigFocus />
      <WhyBigData />
      <LetsConnect
        title={"Ready to Scale with Big Data?"}
        content={
          "Partner with us to build powerful Big Data solutions that accelerate growth."
        }
      />
    </>
  );
}

export default BigDataPage;
