export const blogs = [
  {
    id: 1,
    title: "Mastering JavaScript: Tips and Tricks",
    content:
      "Explore the most effective tips and tricks for mastering JavaScript, from ES6 features to modern frameworks.",
    category: "Programming",
    publisher: "John Doe",
    date: "11 Jan 2024",
    readLength: "7 min read",
    img: "https://example.com/js-tips-tricks.jpg",
    publisher_avatar: "https://example.com/avatars/johndoe.jpg",
  },
  {
    id: 2,
    title: "CSS Grid vs Flexbox: Which Should You Use?",
    content:
      "A deep dive into the pros and cons of CSS Grid and Flexbox for modern web design.",
    category: "Web Development",
    publisher: "Jane Smith",
    date: "8 Jan 2024",
    readLength: "5 min read",
    img: "https://example.com/css-grid-flexbox.jpg",
    publisher_avatar: "https://example.com/avatars/janesmith.jpg",
  },
  {
    id: 3,
    title: "How to Build a Full-Stack MERN Application",
    content:
      "Learn how to create a full-stack MERN application from scratch, using MongoDB, Express, React, and Node.js.",
    category: "Full Stack Development",
    publisher: "Ajay Kasturi",
    date: "15 Feb 2024",
    readLength: "10 min read",
    img: "https://example.com/mern-fullstack.jpg",
    publisher_avatar: "https://example.com/avatars/ajaykasturi.jpg",
  },
  {
    id: 4,
    title: "AI and Its Impact on Software Development",
    content:
      "An insightful look at how AI is transforming the landscape of software development.",
    category: "AI & ML",
    publisher: "Alice Williams",
    date: "20 Jan 2024",
    readLength: "6 min read",
    img: "https://example.com/ai-software-dev.jpg",
    publisher_avatar: "https://example.com/avatars/alicewilliams.jpg",
  },
  {
    id: 5,
    title: "A Guide to Responsive Web Design",
    content:
      "Learn how to create responsive websites that look great on any device with these practical tips.",
    category: "Web Design",
    publisher: "Mark Johnson",
    date: "5 Feb 2024",
    readLength: "8 min read",
    img: "https://example.com/responsive-web-design.jpg",
    publisher_avatar: "https://example.com/avatars/markjohnson.jpg",
  },
  {
    id: 6,
    title: "Tailwind CSS vs Bootstrap: A Detailed Comparison",
    content:
      "Understand the key differences between Tailwind CSS and Bootstrap for building modern, responsive websites.",
    category: "CSS Frameworks",
    publisher: "Emily Brown",
    date: "22 Jan 2024",
    readLength: "6 min read",
    img: "https://example.com/tailwind-bootstrap.jpg",
    publisher_avatar: "https://example.com/avatars/emilybrown.jpg",
  },
  {
    id: 7,
    title: "Building Scalable Docker Containers",
    content:
      "Discover best practices for building scalable and efficient Docker containers for large applications.",
    category: "DevOps",
    publisher: "Michael Lee",
    date: "29 Jan 2024",
    readLength: "9 min read",
    img: "https://example.com/docker-scalable.jpg",
    publisher_avatar: "https://example.com/avatars/michaellee.jpg",
  },
  {
    id: 8,
    title: "Introduction to Cloud Computing",
    content:
      "A beginner’s guide to cloud computing, covering key concepts, types, and services.",
    category: "Cloud Computing",
    publisher: "Sophia White",
    date: "17 Jan 2024",
    readLength: "5 min read",
    img: "https://example.com/cloud-computing-intro.jpg",
    publisher_avatar: "https://example.com/avatars/sophiawhite.jpg",
  },
  {
    id: 9,
    title: "React vs Angular: A Comprehensive Comparison",
    content:
      "A detailed comparison between React and Angular to help you decide which one to use for your next project.",
    category: "Frontend Frameworks",
    publisher: "David Clark",
    date: "12 Jan 2024",
    readLength: "7 min read",
    img: "https://example.com/react-vs-angular.jpg",
    publisher_avatar: "https://example.com/avatars/davidclark.jpg",
  },
  {
    id: 10,
    title: "Exploring the Power of TypeScript in Web Development",
    content:
      "An overview of how TypeScript can enhance JavaScript development with type safety and modern features.",
    category: "Programming",
    publisher: "Olivia Martinez",
    date: "25 Jan 2024",
    readLength: "6 min read",
    img: "https://example.com/typescript-webdev.jpg",
    publisher_avatar: "https://example.com/avatars/oliviamartinez.jpg",
  },
];
